# Generated by Django 3.1.5 on 2021-04-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210411_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
        migrations.AlterField(
            model_name='cart',
            name='books',
            field=models.ManyToManyField(null=True, to='book.Book'),
        ),
    ]
